Repository Colm3na/polkastats-backend-v3, pull requests merged in 2020-03, with the labels that each got.

#42 add substrate node as compose dependence
  docker/polkastats-backend/docker-compose.yml
Labels: enhancement

#45 Fred/41 update readme
  README.md
Labels: documentation

#32 Phragmen crawler and docker
  crawlers/phragmen.js
  docker/polkastats-backend/docker-compose.yml
  docker/polkastats-backend/phragmen/Dockerfile
  docker/polkastats-backend/sql/polkastats.sql
Labels: bug

#44 Add new crawlers to the script
  docker/polkastats-backend/clean-polkastats-dockers
  package.json
Labels: dockers

#56 Add new service and fix some paths
  backend.config.js
  docker/polkastats-backend/docker-compose.yml
  package.json
Labels: dockers

#58 Update documentation and backup scripts
  README.md
  docker/polkastats-backend/substrate-client/restore-backup
  docker/polkastats-backend/substrate-client/start-backup
Labels: documentation

#66 Fix bugs introduced in graph data
  lib/BackendV3.js
  lib/crawlers/staking.js
Labels: bug

#71 Update hasura image
  docker/polkastats-backend/docker-compose.yml
Labels: enhancement

#73 Update polkadot daemon
  docker/polkastats-backend/substrate-client/Dockerfile
Labels: dockers

#69 Disable crawlers through config
  backend.config.js
  index.js
  lib/BackendV3.js
  lib/crawlers/activeAccounts.js
  lib/crawlers/blockHarvester.js
  lib/crawlers/blockListener.js
  lib/crawlers/phragmen.js
  lib/crawlers/rewards.js
  lib/crawlers/staking.js
Labels: enhancement

#88 New v0.7.26 substrate node
  docker/polkastats-backend/substrate-client/Dockerfile
Labels: dockers

#82 [WIP] Comment out the build process and download the binary
  docker/polkastats-backend/backend/Dockerfile
Labels: dockers, enhancement, help wanted

#102 Fredy/mileston1 doc
  README.md
  backend.config.js
  docker/polkastats-backend/substrate-client/Dockerfile
  images/hasura-data.png
  images/hasura-track.png
Labels: Milestone 1, documentation
